development:
  #---------------- Twilio credentials----------------
  TWILIO_ACCOUNT_SID: TWILLO ACCOUNT SID
  TWILIO_AUTH_TOKEN: TWILLO TOKEN
  TWILIO_PHONE_NUMBER: TWILLO_PHONENO
  #---------Social authentication credentials---------
  FACEBOOK_KEY: FACEBOOK_APP_KEY
  FACEBOOK_SECRET: FACEBOOK_SECRET_KEY
  TWITTER_KEY: TWITTER_APP_KEY
  TWITTER_SECRET: TWITTER_SECRET_KEY

  #mandrill api key
  Mandrill: MANDRILL_KEY

  #cloud_front_url for image
  cloud_front_url: CLOUDFRONT_IMAGE_URL

  #mailling credentials
  Mailer_Email: MAILER_EMAIL
  Mailer_Password: MAILER_PASSWORD

  #---------------- Amazon and S3 credentials----------------
  S3_KEY: AWS_S3_KEY
  S3_SECRET: AWS_S3_SECRET
  S3_INPUT_BUCKET: INPUT_VIDEO
  S3_OUTPUT_BUCKET: S3_OUTPUT_BUCKET
  S3_VIDEO_REGION: us-west-1

  #host url
  Host: REACT_HOST
  RAILS_HOST: RAILS_HOST
  RAILS_DEFAULT_URL_HOST: RAILS_DEFAULT_URL_HOST
  BLOG_HOST: BLOG_HOST

  # Staff Login url for blog feature.
  BLOG_LOGIN_URL: "https://stag-blog.localhost:3000/users/sign_in"

  #sidekiq credentials
  SideKiq_UserName: SIDEKIQ_LOGIN_USERNAME
  SideKiq_Password: SIDEKIQ_LOGIN_PASSWORD

  #social_return_url
  SocialReturn: Url_of_Page_Return_after_social_signup_form_react

  #Bitly credentials
  Bitly_access_token: BITLY_ACCESSTOKEN

  # App token for access react api
  HTTP_X_CLIENT_TOKEN: Token

  #smart_url https://manage.smarturl.it/
  smart_url: URL_For_Making_Play_Store_Link

  #for push notification on android devise
  FCM_API_KEY: FCM_API_KEY

  # -----ios development arn-----for push notifications on ios devise
  IOS_ARN: IOS_ARN
  receipt_url: RECEIPT_URL
  iOS_password: IOS_PASSWORD

  # STRIPE
  PUBLISHABLE_KEY: stripe_puplish_key
  SECRET_KEY: stripe_secret_key

  # PAYPAL
  Paypal_Username: Paypal_Username
  Paypal_Password: Paypal_Password
  Paypal_signature: Paypal_signature

  #---------------- paypal sandbox credentials----------------
  PAYPAL_CLIENT_ID: PAYPAL_CLIENT_ID
  PAYPAL_CLIENT_SECRET: PAYPAL_CLIENT_SECRET
  PAYPAL_TOKEN_URL: PAYPAL_TOKEN_URL
  PAYPAL_BILLING_AGREEMENTS_URL: PAYPAL_BILLING_AGREEMENTS_URL
  PAYPAL_BILLING_PLAN_URL: PAYPAL_BILLING_PLAN_URL
  PAYPAL_HOST: PAYPAL_HOST
  APP_HOST: APP_HOST
