development:
  access_key_id: "AKIAIJXUUTOS4BFWXDJA"
  secret_access_key: "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"
  bucket: "miniflix-development"
  revision: ENV['Revision']

production:
  access_key_id: "AKIAIJXUUTOS4BFWXDJA"
  secret_access_key: "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"
  bucket: "miniflix-video"
  revision: ENV['Revision']

staging:
  access_key_id: "AKIAIJXUUTOS4BFWXDJA"
  secret_access_key: "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"
  bucket: "miniflix-staging-video"
  revision: ENV['Revision']

test:
  access_key_id: "AKIAIJXUUTOS4BFWXDJA"
  secret_access_key: "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"
  bucket: "miniflix-text-video"
  revision: ENV['Revision']
